spring:
  data:
#    mongodb:
#      user: mongoadmin
#      password: secret
##      uri: mongodb://host:27017/testDB
#      uri: mongodb://mongoadmin:secret@localhost:27017/?authSource=admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

