spring:
  data:
    mongodb:
#      user: testuser
#      password: secret
##      uri: mongodb://host:27017/testDB
#      uri: mongodb://mongoadmin:secret@localhost:27017/?authSource=admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    consumer:
      bootstarp-servers: localhost:9092
      group-id: "random_group_id"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstarp-servers: locahost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

